services:
  PresenteProfessor:
    image: presente_professor:latest
    container_name: PresenteProfessor
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "3000:3000"
    volumes:
      - Data:/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
volumes:
  Data: